#!/usr/bin/env python3
"""Find likely fourth-wall narration in a Folloze HTML file."""

from __future__ import annotations

import argparse
import html
import json
import re
from html.parser import HTMLParser
from pathlib import Path
from typing import NamedTuple


PHRASES = (
    "this board",
    "this page",
    "this experience",
    "this section",
    "demo board",
    "demo experience",
    "content magic",
    "built with",
    "created with",
    "generated by",
    "powered by ai",
    "pdf wrapper",
    "static pdf",
    "interactive journey",
    "real interaction",
    "not decorative",
    "the panel changes",
    "what the rep should",
    "demo agenda",
    "sales motion",
    "before and after",
)

CONTEXT_TERMS = (
    "prompt",
    "skill",
    "template",
    "prototype",
    "sample",
    "placeholder",
    "proof section",
    "preview",
    "generated",
)

PLACEHOLDER_PATTERN = re.compile(
    r"\[(?:TBD|TODO|CONFIRM|PLACEHOLDER|[A-Z][A-Z0-9 _-]{1,50})[^\]]{0,80}\]"
)
DATA_URI_PATTERN = re.compile(
    r"data:(?:image|font)/[^;,\"']+(?:;[^,]*)?,[A-Za-z0-9+/=%_-]+",
    re.IGNORECASE,
)
SPACE_PATTERN = re.compile(r"\s+")
SCRIPT_STRING_PATTERN = re.compile(
    r"""(?P<quote>["'`])(?P<value>(?:\\.|(?!\1).)*)(?P=quote)""",
    re.DOTALL,
)
CSS_CONTENT_PATTERN = re.compile(
    r"""content\s*:\s*(?P<quote>["'])(?P<value>(?:\\.|(?!\1).)*)(?P=quote)""",
    re.IGNORECASE | re.DOTALL,
)
BUYER_COPY_ATTRIBUTES = {
    "alt",
    "aria-description",
    "aria-label",
    "placeholder",
    "title",
    "value",
}


class Candidate(NamedTuple):
    line: int
    surface: str
    text: str


class CopyExtractor(HTMLParser):
    def __init__(self) -> None:
        super().__init__(convert_charrefs=True)
        self.candidates: list[Candidate] = []
        self._style_depth = 0
        self._script_depth = 0

    def handle_starttag(
        self, tag: str, attrs: list[tuple[str, str | None]]
    ) -> None:
        lowered_tag = tag.lower()
        if lowered_tag == "style":
            self._style_depth += 1
        elif lowered_tag == "script":
            self._script_depth += 1

        line, _ = self.getpos()
        for name, value in attrs:
            lowered_name = name.lower()
            if not value or lowered_name in {"href", "src", "style", "onclick"}:
                continue
            if lowered_name in BUYER_COPY_ATTRIBUTES or lowered_name.startswith("data-"):
                self.candidates.append(
                    Candidate(line, f"attribute:{lowered_name}", value)
                )

    def handle_endtag(self, tag: str) -> None:
        lowered_tag = tag.lower()
        if lowered_tag == "style" and self._style_depth:
            self._style_depth -= 1
        elif lowered_tag == "script" and self._script_depth:
            self._script_depth -= 1

    def handle_data(self, data: str) -> None:
        if self._style_depth:
            line, _ = self.getpos()
            for match in CSS_CONTENT_PATTERN.finditer(data):
                value = match.group("value")
                if value.strip():
                    self.candidates.append(
                        Candidate(
                            line + data[: match.start()].count("\n"),
                            "css-generated-content",
                            value,
                        )
                    )
            return

        line, _ = self.getpos()
        if self._script_depth:
            for match in SCRIPT_STRING_PATTERN.finditer(data):
                value = match.group("value")
                if re.search(r"[A-Za-z]{3}", value):
                    self.candidates.append(
                        Candidate(
                            line + data[: match.start()].count("\n"),
                            "script-string",
                            value,
                        )
                    )
            return

        if data.strip():
            self.candidates.append(Candidate(line, "visible-text", data))

    def handle_comment(self, data: str) -> None:
        if data.strip():
            line, _ = self.getpos()
            self.candidates.append(Candidate(line, "html-comment", data))


def excerpt(line: str, start: int, width: int = 180) -> str:
    left = max(0, start - width // 3)
    right = min(len(line), left + width)
    text = SPACE_PATTERN.sub(" ", line[left:right]).strip()
    if left:
        text = "..." + text
    if right < len(line):
        text += "..."
    return text


def scan(path: Path) -> list[dict[str, object]]:
    findings: list[dict[str, object]] = []
    extractor = CopyExtractor()
    extractor.feed(path.read_text(encoding="utf-8"))

    for candidate in extractor.candidates:
        sanitized = DATA_URI_PATTERN.sub("[data-uri]", html.unescape(candidate.text))
        lowered = sanitized.lower()

        for phrase in PHRASES:
            offset = lowered.find(phrase)
            if offset >= 0:
                findings.append(
                    {
                        "line": candidate.line,
                        "surface": candidate.surface,
                        "match": phrase,
                        "severity": "high",
                        "excerpt": excerpt(sanitized, offset),
                    }
                )

        for term in CONTEXT_TERMS:
            for match in re.finditer(rf"\b{re.escape(term)}\b", lowered):
                findings.append(
                    {
                        "line": candidate.line,
                        "surface": candidate.surface,
                        "match": term,
                        "severity": "review",
                        "excerpt": excerpt(sanitized, match.start()),
                    }
                )

        for match in PLACEHOLDER_PATTERN.finditer(sanitized):
            findings.append(
                {
                    "line": candidate.line,
                    "surface": candidate.surface,
                    "match": match.group(0),
                    "severity": "high",
                    "excerpt": excerpt(sanitized, match.start()),
                }
            )

    return findings


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Find likely fourth-wall narration and placeholders in Folloze HTML."
    )
    parser.add_argument("html_file", type=Path)
    parser.add_argument(
        "--fail-on-findings",
        action="store_true",
        help="Exit with status 1 when review candidates are found.",
    )
    args = parser.parse_args()

    if not args.html_file.is_file():
        parser.error(f"file does not exist: {args.html_file}")

    findings = scan(args.html_file)
    result = {
        "file": str(args.html_file.resolve()),
        "finding_count": len(findings),
        "high_count": sum(item["severity"] == "high" for item in findings),
        "review_count": sum(item["severity"] == "review" for item in findings),
        "findings": findings,
    }
    print(json.dumps(result, indent=2))
    return 1 if findings and args.fail_on_findings else 0


if __name__ == "__main__":
    raise SystemExit(main())
