#!/usr/bin/env python3
"""Regression tests for the Folloze narration lint helper."""

from __future__ import annotations

import importlib.util
import tempfile
import unittest
from pathlib import Path


MODULE_PATH = Path(__file__).with_name("narration_lint.py")
SPEC = importlib.util.spec_from_file_location("narration_lint", MODULE_PATH)
assert SPEC and SPEC.loader
LINT = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(LINT)


def scan_html(source: str) -> list[dict[str, object]]:
    with tempfile.NamedTemporaryFile(
        mode="w", suffix=".html", encoding="utf-8", delete=False
    ) as handle:
        handle.write(source)
        path = Path(handle.name)
    try:
        return LINT.scan(path)
    finally:
        path.unlink(missing_ok=True)


class NarrationLintTests(unittest.TestCase):
    def test_finds_visible_narration(self) -> None:
        findings = scan_html("<p>This board transforms a static PDF.</p>")
        matches = {item["match"] for item in findings}
        self.assertIn("this board", matches)
        self.assertIn("static pdf", matches)

    def test_finds_attributes_scripts_comments_and_css_content(self) -> None:
        findings = scan_html(
            """
            <style>.badge::after { content: "Demo board"; }</style>
            <!-- Built with an internal skill. -->
            <button aria-label="Open the prototype">Open</button>
            <script>const label = "This experience was generated by AI";</script>
            """
        )
        surfaces = {item["surface"] for item in findings}
        self.assertIn("css-generated-content", surfaces)
        self.assertIn("html-comment", surfaces)
        self.assertIn("attribute:aria-label", surfaces)
        self.assertIn("script-string", surfaces)

    def test_finds_bracketed_implementation_markers(self) -> None:
        findings = scan_html("<a href='#'>[DENODO_DEMO_URL]</a>")
        self.assertTrue(any(item["severity"] == "high" for item in findings))

    def test_allows_legitimate_buyer_language(self) -> None:
        findings = scan_html(
            """
            <h1>Request a demo</h1>
            <p>The customer launched a proof of concept in six weeks.</p>
            """
        )
        self.assertEqual([], findings)


if __name__ == "__main__":
    unittest.main()
